### ISSUE TITLE
function of detailed itineraries of many to many

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#6] opened 2020-08-14 14:58 UTC

**Comment by dhersz** [comment] 2020-08-14 22:01
Some suggestions for this function (based on what I've seen in `r5_plan_single_trip()`):

- Instead of `fromLat`, `fromLon`, `toLat`, `toLon`, define origins and destinations as `data.frame`s with columns `id`, `lat` and `lon` (maybe only `lat` and `lon` as mandatory and we add an `id` if there is not one set already). Then calculate the itineraries from all origins to all destinations.

- Instead of having two distinct parameters `direct_mode` and `transit_mode`, keep only a parameter `mode`. This could default to a specific mode, and all the modes supportes by R5 (WALK, CAR, BUS, etc.) are possible entries. If there isn't a similar thing implemented in R5 already we could use TRANSIT as a handy aggregator of all possible transit modes.

**Comment by mvpsaraiva** [comment] 2020-08-15 14:22
I've added the planMultipleTrips function to the Java api and upated the JAR file.

8efca44

**Comment by mvpsaraiva** [comment] 2020-08-15 14:23
Rafa, can you update the JAR file in the server?
https://drive.google.com/drive/folders/1VWy4dnFruADNe6RMVaSB8jt2YbGs4AH9?usp=sharing
@rafapereirabr

**Comment by mvpsaraiva** [comment] 2020-08-15 14:31
I've added a multiple_detailed_itineraries function for tests. This shall be merged to detailed_itinerarires  in the future. You can test the function with the following code:

 
 library(r5r)
 library(data.table)
 library(dplyr)
 library(sf)
 
 # build transport network
 path <- system.file("extdata", package = "r5r")
 r5_core <- setup_r5(data_path = path)

 # load origin/destination points
 points <- read.csv(system.file("extdata/poa_hexgrid.csv", package = "r5r"))

 # input
 trip_date <- "2019-03-17"
 departure_time <- "14:00:00"
 street_time = 15L
 direct_modes <- c("WALK", "BICYCLE", "CAR")
 transit_modes <-"BUS"
 max_street_time = 30
 
trip_requests <- data.frame(id = 1:5,
                            fromLat = points[1:5,]$lat,
                            fromLon = points[1:5,]$lon,
                            toLat = points[96:100,]$lat,
                            toLon = points[96:100,]$lon )

trips <- multiple_detailed_itineraries( r5_core,
                                         trip_requests,
                                         trip_date = trip_date,
                                         departure_time = departure_time,
                                         direct_modes = direct_modes,
                                         transit_modes = transit_modes,
                                         max_street_time = max_street_time
                                         )

**Comment by rafapereirabr** [comment] 2020-08-16 00:58
> https://drive.google.com/drive/folders/1VWy4dnFruADNe6RMVaSB8jt2YbGs4AH9?usp=sharing

Done!

**Comment by rafapereirabr** [comment] 2020-08-16 02:13
This [flow chart](https://github.com/buma/R5Docs) gives an overview of R5 documentation. Reflecting on it, I think the `detailed itineraries` function should also include the following outputs:

- [ ] waiting_time
- [ ] walk_time
- [ ] total_distance
- [ ] transfers
- [ ] duration

**Comment by mvpsaraiva** [comment] 2020-08-19 22:48
Mostly done. I have added the waiting times and distance travelled in each of the trip's segment. However, R5 doesn't return the distance of transit segments. It also depends on the shape being available in the input GTFS. We can calculate distance in R using the geometry column, but I think transit stops are connected through straight lines and not the actual route's geometry.

**Comment by dhersz** [comment] 2020-08-20 03:23
Something funky is going on with each segment distance. See below:

```r
data_path <- system.file("extdata", package = "r5r")
r5r_core <- setup_r5(data_path = data_path)

# load and set origin/destination points
points <- read.csv(file.path(data_path, "poa_points_of_interest.csv"))

origins <- points[10,]
destinations <- points[12,]

# inputs
mode = c("WALK", "BUS")
departure_time <- "14:00:00"
trip_date <- "2019-03-15"
max_walk_dist <- 1

df <- detailed_itineraries(r5r_core,
                           origins,
                           destinations,
                           trip_date,
                           departure_time,
                           max_walk_dist,
                           mode)
```
```
> df
Simple feature collection with 3 features and 13 fields
geometry type:  LINESTRING
dimension:      XY
bbox:           xmin: -51.22972 ymin: -30.07325 xmax: -51.17479 ymax: -29.99884
geographic CRS: WGS 84
            fromId                           toId   fromLat   fromLon     toLat     toLon option segment
1 farrapos_station praia_de_belas_shopping_center -29.99772 -51.19762 -30.04995 -51.22875     11       1
2 farrapos_station praia_de_belas_shopping_center -29.99772 -51.19762 -30.04995 -51.22875     11       2
3 farrapos_station praia_de_belas_shopping_center -29.99772 -51.19762 -30.04995 -51.22875     11       3
  mode duration distance  route wait                       geometry
1 WALK      523   551820           0 LINESTRING (-51.19807 -29.9...
2  BUS     2760       -1 poa:T2  377 LINESTRING (-51.1995 -30.00...
3 WALK      493   483959           0 LINESTRING (-51.22846 -30.0...
```

**Comment by rafapereirabr** [comment] 2020-08-20 11:27
That's really strange. We can use `sf::st_length` to get the distances as well but I guess it would be more efficient to get this info from R5, specially for really large outputs.
 
```
df$dist = sf::st_length(df)
df

            fromId                           toId   fromLat   fromLon     toLat     toLon option segment
1 farrapos_station praia_de_belas_shopping_center -29.99772 -51.19762 -30.04995 -51.22875     11       1
2 farrapos_station praia_de_belas_shopping_center -29.99772 -51.19762 -30.04995 -51.22875     11       2
3 farrapos_station praia_de_belas_shopping_center -29.99772 -51.19762 -30.04995 -51.22875     11       3
  mode duration distance  route wait                       geometry           dist
1 WALK      523   551820           0 LINESTRING (-51.19807 -29.9...   419.8404 [m]
2  BUS     2760       -1 poa:T2  377 LINESTRING (-51.1995 -30.00... 15269.4134 [m]
3 WALK      493   483959           0 LINESTRING (-51.22846 -30.0...   483.3606 [m]
```

**Comment by dhersz** [comment] 2020-08-25 19:53
@mvpsaraiva I tried plotting the result of detailed_itineraries with mapview and the results seem to align alright with the street network. Sometimes it's a bit off (even more than a bit, actually), but in its majority the shape fits the network. I wonder if these misalignments are caused by the gtfs? Not sure. Check below:

```r
data_path <- system.file("extdata", package = "r5r")
r5r_obj <- setup_r5(data_path = data_path)
points <- read.csv(file.path(data_path, "poa_points_of_interest.csv"))

# inputs
origins <- points[10,]
destinations <- points[12,]
mode <- c("WALK", "TRANSIT")
max_walk_dist <- 1000
max_trip_duration <- 120L
departure_datetime <- as.POSIXct("13-03-2019 14:00:00",
                                 format = "%d-%m-%Y %H:%M:%S")

df <- detailed_itineraries(r5r_obj,
                           origins,
                           destinations,
                           mode,
                           departure_datetime,
                           max_walk_dist)

stop_r5(r5r_obj)
rJava::.jgc(R.gc = TRUE)

mapview::mapview(df)
```

![image](https://user-images.githubusercontent.com/1557047/91220861-32168700-e6f3-11ea-853f-d7df810e9fef.png)

Zoom in on some "offtrack" parts:

![image](https://user-images.githubusercontent.com/1557047/91220922-4bb7ce80-e6f3-11ea-8334-12b32c26421b.png)

**Comment by mvpsaraiva** [comment] 2020-08-25 19:57
The problem is, that route should look like this, according to the `shape` in the GTFS :

![image](https://user-images.githubusercontent.com/7387691/91221330-e1ebf480-e6f3-11ea-8ec6-c236700fb803.png)

**Comment by mvpsaraiva** [comment] 2020-08-25 20:12
I've been trying to fix this for a while now, but sometimes the fix can be worse than the actual problem. First, I've managed to collect the actual route's geometry from the `shapes.txt` file in the GTFS, and extract the segment between bus stops. You can see in my previous comment that, in that particular case, the route aligns nicely to the street network.

The problem is that in some cases, the geometry in the `shapes.txt` file is not trustworthy at all. In one of my tests, a segment that should be no more than 2 km long ended up being almost 60 km long. So, it really depends on the quality of the GTFS file. 

So, I think we have a few options:
1. Leave the resulting geometry as it is now: a series of straight lines connecting transit stops. If the input GTFS file does not have a `shapes.txt` in it, this is the only possible option.
2. Extract the true geometry of the itinerary, even though this can generate very weird results in some cases. I believe the user of the package can fix those in GIS later, if necessary. 
3. Add an option to retrieve the complete or simplified geometry in `detailed_itineraries`, so if something goes wrong with the complete geometry the user can run the function again, but asking for the simplified geometry (the one from option 1).

**Comment by rafapereirabr** [comment] 2020-08-25 20:17
I suggest we stick with option 2. The geometry output of public transport routes should match the `shapes.txt` file in the GTFS. If the GTFS feed has no `shapes.txt`, then our geometry column in our output should be empty.

**Comment by mvpsaraiva** [comment] 2020-08-25 20:39
> I suggest we stick with option 2. The geometry output of public transport routes should match the `shapes.txt` file in the GTFS. If the GTFS feed has no `shapes.txt`, then our geometry column in our output should be empty.

Ok. It's almost done, just need some more tests.

**Comment by dhersz** [comment] 2020-08-26 22:51
I still get the same problem with the new jar. The geometry I'm getting is the same I posted above.

**Comment by mvpsaraiva** [comment] 2020-08-27 14:08
It seems to be working ok here. The path is nicely following the the route's geometry.

![image](https://user-images.githubusercontent.com/7387691/91452724-4e323980-e855-11ea-8656-e8ed515f56cf.png)

Can you update and check again, @dhersz?

**Comment by dhersz** [comment] 2020-08-27 15:31
Cool, it's working now. I had to delete the `network.dat` and `mapdb`s files in my sample data folder and rebuild the network.

![image](https://user-images.githubusercontent.com/1557047/91462974-3365c200-e861-11ea-8b14-c058f9ce8e0e.png)

**Closed by dhersz** 2020-08-27 15:31 UTC
Labels: priority
