### ISSUE TITLE
network.dat not built after running setup_r5

### ISSUE THREAD

**Issue by ny1526** [ipeaGIT/r5r#383] opened 2024-04-26 00:25 UTC
Hello, Thank you so much for creating this very useful package.

I am having some issues getting set up and started with r5r. I have downloaded an OSM dataset and a GTFS feed for the Ile-de-France region. When I run the following setup code:
```
options(java.parameters = "-Xmx2G")

library(r5r)
library(data.table)

folder <- "/Users/ny1526/Desktop/paris_inputs/"

r5r_core <- setup_r5(data_path = folder, verbose = FALSE)

```
I get the following messages, which do not seem to show any errors:
```
No raster .tif files found. Using elevation = 'NONE'.
Using cached R5 version from /Users/ny1526/Library/Caches/org.R-project.R/R/r5r/r5_jar_v7.1.0/r5-v7.1-all.jar

Finished building network.dat at /Users/ny1526/Desktop/paris_inputs//network.dat
```
However, in spite of the last message, no network.dat file is outputted in the specified directory.

Can you help me understand what might be the source of this issue? I used the package a couple years ago on a different dataset and did not run into these issues. Thank you very much for your help!

**Comment by rafapereirabr** [comment] 2024-04-26 00:55
Pleasr run the `r5r::r5r_sitrep()` function to generate a situation report, and paste the output along with your issue. This will help us find eventual bugs.

**Comment by ny1526** [comment] 2024-04-26 13:26
Thank you for the response. Below is the output after running `r5r_sitrep()`:
```
$r5r_package_version
[1] ‘2.0.9999’

$r5_jar_version
[1] "7.1"

$java_version
[1] "21.0.2"

$set_memory
[1] "-Xmx2G"

$session_info
R version 4.3.1 (2023-06-16)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.4.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.15.4 r5r_2.0.09999    

loaded via a namespace (and not attached):
[1] compiler_4.3.1    backports_1.4.1   tools_4.3.1       rstudioapi_0.15.0 checkmate_2.3.1   rJava_1.0-11     

```

**Comment by rafapereirabr** [comment] 2024-04-26 13:37
1. Can you run the reproducible examples of any functions in the package?
2. Do you have permission to write at this folder?
3. If you run `list.files(folder)`, what output do you get ?

**Comment by ny1526** [comment] 2024-04-26 13:52
1. Yes, when I run the example with the data in the package, it seems to work (in that it successfully creates a network.dat file.)
2. Yes, I have permissions to write to this folder.
3. These are the files listed after I run the setup function (after starting just with the GTFS zipped folder and the osm.pbf file, so it creates the other two files):
```
> list.files(folder)
[1] "IDFM-gtfs.zip"                        "ile-de-france-latest.osm.pbf"         "ile-de-france-latest.osm.pbf.mapdb"  
[4] "ile-de-france-latest.osm.pbf.mapdb.p"
```

**Comment by rafapereirabr** [comment] 2024-04-26 19:34
right now,  I suspect this might be realted to an issue with your data set, but I'm not sure. Could you please try running `setup_r5(data_path = folder, overwrite = TRUE)` on another folder with data from another location?

**Comment by ny1526** [comment] 2024-04-27 20:25
I think you are right about the issue with the dataset. I tried running the code on a different dataset and it worked.

I then also tried running the code on the same OSM dataset I was using above but removing the GTFS zipped file from the directory and this time it worked in generating a `network.dat` file. (I previously tried this before and it did not work, so I am not sure what changed.)

If you have advice on what may be the issue with the GTFS file, I would really appreciate it.

**Comment by rafapereirabr** [comment] 2024-04-27 21:27
Ok. I'm glad to hear it is not an issue with r5r but an issue with the GTFS data.
Your GTFS feed might not be valid because of various types os errors. I'd strongly recommend using the feed validator from the [gtfstools](https://ipeagit.github.io/gtfstools/articles/validating.html) package.

Closing this issue now since this is not a problem with r5r.

**Closed by rafapereirabr** 2024-04-27 21:27 UTC

**Comment by ny1526** [comment] 2024-04-29 13:43
Got it, thank you very much for all your help!
