### ISSUE TITLE
Java integration issue

### ISSUE THREAD

**Issue by mplesons** [ipeaGIT/r5r#374] opened 2024-02-29 15:32 UTC
Hello, I am trying to run an analysis using the 'r5r' package, which requires Java integration. However, I'm receiving an error message and I'm not sure how to resolve it. I've attached the outputs of xfun::session_info(). Any help would be much appreciated!
<img width="448" alt="xfunoutput" src="https://github.com/ipeaGIT/r5r/assets/143037134/53920d79-fc4e-4bf8-b031-bca4abfe0116">

Here is my code:
              # Install packages
              install.packages('r5r')
              install.packages('tidyverse')
              install.packages("osmextract")
              install.packages('tidytransit')
              
              # Increase Java memory
              options(java.parameters = "-Xmx4G")
              
              # Load other packages
              library(r5r)
              library(osmextract)
              library(sf)
              library(data.table)
              library(ggplot2)
              library(tidytransit)
              
              # Establish Data Path
              data_path <- "/Users/marinaplesons/Documents/RStudio/Methadone Mapping/Datapath"
              list.files(data_path)
              
              # Load Points of Interest
              poi <- fread(file.path(data_path, "POI.csv"))
              head(poi)
              
              # Load Origins
              origins <- fread(file.path(data_path, "Origins.csv"))
              head(origins)
              
              # Build routable transport network
              r5r_core <- setup_r5(data_path = data_path, verbose = FALSE)

And here is the error message I receive with the last code segment:
              > r5r_core <- setup_r5(data_path = data_path, verbose = FALSE)
              No raster .tif files found. Using elevation = 'NONE'.
              Downloading R5 jar file to /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/r5r/jar/r5-v6.9-all.jar
              Error in setup_r5(data_path = data_path, verbose = FALSE) : 
                java.lang.BootstrapMethodError: bootstrap method initialization exception

**Comment by rafapereirabr** [comment] 2024-02-29 23:07
Please run `r5r::r5r_sitrep()` and post below the situation report

**Comment by mplesons** [comment] 2024-02-29 23:57
Thank you very much. Here is the situation report: 

$r5r_package_version
[1] ‘1.1.0’

$r5_jar_version
character(0)

$java_version
[1] "11.0.22"

$set_memory
[1] "-Xmx10G"

$session_info
R version 4.3.3 RC (2024-02-22 r85995)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.5.0     data.table_1.15.0 sf_1.0-15         r5r_1.1.0        

loaded via a namespace (and not attached):
 [1] vctrs_0.6.5        cli_3.6.2          rlang_1.1.3        DBI_1.2.2          KernSmooth_2.23-22
 [6] generics_0.1.3     rJava_1.0-11       glue_1.7.0         colorspace_2.1-0   e1071_1.7-14      
[11] scales_1.3.0       fansi_1.0.6        grid_4.3.3         munsell_0.5.0      classInt_0.4-10   
[16] tibble_3.2.1       lifecycle_1.0.4    compiler_4.3.3     dplyr_1.1.4        Rcpp_1.0.12       
[21] pkgconfig_2.0.3    rstudioapi_0.15.0  R6_2.5.1           class_7.3-22       tidyselect_1.2.0  
[26] utf8_1.2.4         pillar_1.9.0       magrittr_2.0.3     withr_3.0.0        tools_4.3.3       
[31] proxy_0.4-27       gtable_0.3.4       units_0.8-5

**Comment by mplesons** [comment] 2024-02-29 23:59
I redownloaded JDK 11 and now RStudio says "R session aborted: fatal error". I tried running it on R and got the following error message:


*** caught segfault ***
address 0xfffffffffffffffc, cause 'invalid permissions'

Traceback:
 1: rJava::.jnew("org.ipea.r5r.R5RCore", data_path, verbose, elevation)
 2: setup_r5(data_path = data_path, verbose = FALSE)
 3: eval(ei, envir)
 4: eval(ei, envir)
 5: withVisible(eval(ei, envir))
 6: source("/Users/marinaplesons/Documents/RStudio/Methadone Mapping/Methadone_Mapping.R")

**Comment by rafapereirabr** [comment] 2024-03-01 00:34
Please restart your R session and try running the code below to see if it works:

```
library(r5r)

# directory with street network and gtfs files
data_path <- system.file("extdata/poa", package = "r5r")

r5r_core <- setup_r5(data_path, overwrite = TRUE)

```

**Comment by mplesons** [comment] 2024-03-01 14:08
Thank you. With that code, I receive the fatal error message in RStudio and the following error message in R:

Downloading R5 jar file to /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/r5r/jar/r5-v6.9-all.jar

 *** caught segfault ***
address 0xfffffffffffffff8, cause 'invalid permissions'

Traceback:
 1: rJava::.jnew("org.ipea.r5r.R5RCore", data_path, verbose, elevation)
 2: setup_r5(data_path, overwrite = TRUE)
 3: eval(ei, envir)
 4: eval(ei, envir)
 5: withVisible(eval(ei, envir))
 6: source("/Users/marinaplesons/Downloads/test.R")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

**Comment by mplesons** [comment] 2024-03-01 15:04
Wow, thank you so much! I did the second option (upgrade to JDK 21 and use the dev version of r5r) and I was able to build the network. I then ran the following code and receive another error message.

**Code:**

# Routing analysis
# set inputs
mode <- c("WALK", "TRANSIT")
max_walk_time <- 30 # minutes
max_trip_duration <- 240 # minutes
departure_datetime <- as.POSIXct("28-02-2024 08:00:00",
                                 format = "%d-%m-%Y %H:%M:%S")

# calculate a travel time matrix
ttm <- travel_time_matrix(r5r_core = r5r_core,
                          origins = origins,
                          destinations = poi,
                          mode = mode,
                          departure_datetime = departure_datetime,
                          max_walk_time = max_walk_time,
                          max_trip_duration = max_trip_duration)

head(ttm)

**Error message:**

Error in .jcall("RJavaTools", "Z", "hasField", .jcast(x, "java/lang/Object"),  : 
  java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "<parameter1>" is null
In addition: Warning messages:
1: In assign_points_input(origins, "origins") :
  'origins$id' forcefully cast to character.
2: In assign_points_input(destinations, "destinations") :
  'destinations$id' forcefully cast to character.

Thank you so much for any guidance!!

**Comment by rafapereirabr** [comment] 2024-03-01 15:29
could you please try running the code below from a new R session? This is the reproducible example that comes in the documentation of the `travel_time_matrix()` function

```
# increase Java memory
options(java.parameters = "-Xmx2G")

library(r5r)

# build transport network
data_path <- system.file("extdata/poa", package = "r5r")
r5r_core <- setup_r5(data_path)

# load origin/destination points
points <- read.csv(file.path(data_path, "poa_points_of_interest.csv"))

departure_datetime <- as.POSIXct(
  "13-05-2019 14:00:00",
  format = "%d-%m-%Y %H:%M:%S"
)

ttm <- travel_time_matrix(
  r5r_core,
  origins = points,
  destinations = points,
  mode = c("WALK", "TRANSIT"),
  departure_datetime = departure_datetime,
  max_trip_duration = 60
)
head(ttm)
 
stop_r5(r5r_core)

```

**Comment by mplesons** [comment] 2024-03-01 15:38
That code ran without any problems! Here is the output:

> head(ttm)
         from_id               to_id travel_time_p50
          <char>              <char>           <int>
1: public_market       public_market               0
2: public_market bus_central_station              14
3: public_market    gasometer_museum              12
4: public_market santa_casa_hospital              15
5: public_market            townhall               3
6: public_market     piratini_palace              17
> stop_r5(r5r_core)
r5r_core has been successfully stopped.

**Comment by rafapereirabr** [comment] 2024-03-01 16:11
Ok, so this is a clear sign that the problem is not the package itself, but likely an issue with your input data. In this case, it's rather difficult to help without a reproducible example.

**Comment by mplesons** [comment] 2024-03-03 18:45
Thank you, Rafael. I was able to run the analysis on a Windows computer.

**Comment by rafapereirabr** [comment] 2024-03-03 22:43
Glad to hear that! Closing this issue for now.

**Closed by rafapereirabr** 2024-03-03 22:43 UTC
