### ISSUE TITLE
Missing all rides through a Station

### ISSUE THREAD

**Issue by kangkandc1** [ipeaGIT/r5r#237] opened 2022-03-21 11:40 UTC
Dear R5R Team Members,
I have encountered an issue while working with the Regional bahn GTFS (https://gtfs.de/de/feeds/de_rv/). 
Description: According to the GTFS data, there is a trip (with trip id : 10304) that runs every weekday (service id:13 ) between the stations 15392 (Köln Wörringen) and 7421 (Kettwig). It starts at 12.32 in station 15392 and reaches  station 7421 at 14:36, and continues on to Essen (11686
) The route id is 67. 

Kettwig(7421) is a small station and route 67 is the only route going through it. However, when I try to create a travel-time matrix with Kettwig as the only origin, (using all other points destinations) I get a empty result. (code below)- I am unable to understand why this may be the case. A manual search of the GTFS data should return at least one trip from Kettwig. I think there may be one problem with the database. The route id , that is 67, is not unique. There are other routes with id 67 which pass through different set of stations. Could this be the reason?

The GTFS feed comes a private aggregator and covers the whole of Germany. Howevery, since there a multiple trains with the same name, multiple routes (by route is mean a list of stations) get assigned the same route id. Could this be throwing off the routing algorithm?

Code:

library(r5r)
library(sf)
library(data.table)
library(ggplot2)
library(mapview)
mapviewOptions(platform = 'leafgl')

options(java.parameters = "-Xmx6G")
setwd('C:/Users/User/Dropbox/PC/Documents/Regional')
data_path='C:/Users/User/Dropbox/PC/Documents/Regional'
r5r_core <- setup_r5(data_path = data_path, verbose = FALSE)

sampled_points<-read.csv('stops.txt')
sampled_points<-data.frame(sampled_points)
head(sampled_points)
O<-data.frame(sampled_points$stop_id,sampled_points$stop_lon,sampled_points$stop_lat)
colnames(O)=c('id','lon','lat')
Kettwig=O[O$id==7421|O$id==843,]
mode <- c("TRANSIT","WALK")
max_walk_dist <- 5000
max_trip_duration <- 600
departure_datetime <- as.POSIXct("18-03-2022 14:00:00",
                                 format = "%d-%m-%Y %H:%M:%S")
ttm <- travel_time_matrix(r5r_core = r5r_core,
                          origins =Kettwig ,
                          destinations = O,
                          mode = mode,
                          time_window = 120,
                          departure_datetime = departure_datetime,
                          max_walk_dist = max_walk_dist,
                          max_trip_duration = max_trip_duration,
                          verbose = FALSE)

head(ttm)

**Manual Search**

K_trip=Stop_times[Stop_times$trip_id==10304,] "get the details of trip 10304"

Service_id=data.frame(read.csv("calendar.txt")) "the tri"
Service_id[Service_id$service_id==13,] % "service id 13 corresponds to all weekdays"

Thanks and Regards

**Comment by mvpsaraiva** [comment] 2022-03-22 13:46
Hi @kangkandc1 

I was going to say that if the issue is due to duplicated route ids, then it's something to be dealt with upstream in R5... there's no much we can do on our side. It's great that @ansoncfit already noticed this issue, I just don't know their plan to deal with this at Conveyal. Technically, I believe that the GTFS needs to be fixed by assigning unique id's to routes, stops and everything else. And I'm not sure this is something that can be done automatically by R5.

Just one more thing I've noticed in your code: the departure time is set to 14:00, but in the issue description you said the trip starts at 12:32. Have you tried earlier departure times?

**Closed** 2022-03-22 15:25 UTC
