### ISSUE TITLE
Travel Time and Detailed Itineraries are different

### ISSUE THREAD

**Issue by yiwenw3** [ipeaGIT/r5r#232] opened 2022-02-27 07:23 UTC
Hi, I am working on creating the travel time and the detailed itineraries for King County. The GTFS data I used for King County Metro is from (https://transitfeeds.com/p/king-county-metro/73/20200129). I am currently meeting an issue that the travel times do not match with each other for ttm and dit. I know these functions use different algorithms, but the differences seem to be a bit large. I have attached the files I used. Also, is there a way to drop the extra trips in ttm, so leftovers of fromId and ToId are consistent?(For example,   I only want fromId 1 and ToId 1,  and want to drop fromId 1 and ToId 2,3...) Thank you for the response!

### code:
```
library(r5r)
library(sf)
library(data.table)

File_Path = file.path("C:","299", "Updated Data", fsep = .Platform$file.sep)
list.files(File_Path)
poi <- fread(file.path(File_Path, "OriginsDestinationsPugetSound.csv"))
head(poi)

r5r_core <- setup_r5(data_path = File_Path, verbose = TRUE)

mode <- c("WALK","TRANSIT")
max_walk_dist <- 1000 
max_trip_duration <- 120

OriginPoint = poi[1:25,2:4]
DestinationPoint = poi[1:25,5:7]
departure_datetime = as.POSIXct("4/16/2020 10:00", format = "%m/%d/%Y %H:%M")
time_window = 60

dit <- detailed_itineraries(r5r_core = r5r_core,
                            origins = OriginPoint,
                            destinations = DestinationPoint,
                            mode = mode,
                            departure_datetime = departure_datetime,
                            max_walk_dist = max_walk_dist,
                            shortest_path = FALSE,
                            verbose = FALSE)

ttm <- travel_time_matrix(r5r_core = r5r_core,
                          origins = OriginPoint,
                          destinations = DestinationPoint,
                          mode = mode,
                          departure_datetime = departure_datetime,
                          max_walk_dist = max_walk_dist,
                          time_window = time_window,
                          max_trip_duration = max_trip_duration,
                          #breakdown = TRUE,
                          verbose = FALSE)

```
[OriginsDestinationsPugetSound.csv](https://github.com/ipeaGIT/r5r/files/8148239/OriginsDestinationsPugetSound.csv)
Network: https://download.geofabrik.de/north-america/us/washington.html

**Comment by rafapereirabr** [comment] 2022-02-27 18:10
Hi @yiwenw3 .

You are currently setting `shortest_path = FALSE` for the `detailed_itineraries()` function. This means that the function will output various alternative itineraries for each origin-destination pairs. The results of the two routing functions are more comparable when `shortest_path`is set to `TRUE`.

Regarding your second question. The two routing functions arrange origin-destination pairs using different approaches.

- The `travel_time_matrix()` function builds an all-to-all matrix, routing all possible combinations between all origin and all destination points. 
- Meanwhile, the `detailed_itineraries()` function builds a one-to-one matrix, so it queries routes between the 1st origin point and the 1st destination point, then the 2nd origin point and the 2nd destination point, and so on.

**Comment by rafapereirabr** [comment] 2022-02-27 18:54
also, using the `time_window` parameter in the `travel_time_matrix()` function makes the output of the two functions less comparable. I've checked the results of the two functions using your data set and the I've found that the differences are smaller than 4 mintutes for all origin-destination pairs, except one. Plase see the code below:

```
options(java.parameters = "-Xmx20G")

library(r5r)
library(data.table)

File_Path = 'C:/Users/user/Downloads/wd'
list.files(File_Path)
poi <- fread(file.path(File_Path, "OriginsDestinationsPugetSound.csv"))
head(poi)

r5r_core <- setup_r5(data_path = File_Path, verbose = F)

mode <- c("WALK","TRANSIT")
max_walk_dist <- 1000 
max_trip_duration <- 120

OriginPoint = poi[1:25,2:4]
DestinationPoint = poi[1:25,5:7]
departure_datetime = as.POSIXct("4/16/2020 10:00", format = "%m/%d/%Y %H:%M")

dit <- detailed_itineraries(r5r_core = r5r_core,
                            origins = OriginPoint,
                            destinations = DestinationPoint,
                            mode = mode,
                            departure_datetime = departure_datetime,
                            max_walk_dist = max_walk_dist,
                            shortest_path = TRUE,
                            verbose = FALSE, 
                            drop_geometry = T)

ttm <- travel_time_matrix(r5r_core = r5r_core,
                          origins = OriginPoint,
                          destinations = DestinationPoint,
                          mode = mode,
                          departure_datetime = departure_datetime,
                          max_walk_dist = max_walk_dist,
                          # time_window = time_window,
                          max_trip_duration = max_trip_duration,
                          verbose = FALSE)
head(ttm)
head(dit)
setDT(dit)

# creat id for origin-destination pair
ttm[, od_id := paste0(fromId, '-', toId), by=.(fromId, toId)]
dit[, od_id := paste0(fromId, '-', toId), by=.(fromId, toId)]

# get total duration of each origin-destination pair
dit_total_time <- dit[, total_duration, by= od_id]

# merge travel times from ttm and dit
df <- merge(dit_total_time, ttm, by='od_id')

# compare differences
summary(df$total_duration - df$travel_time)

> Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
> -18.5667  -4.7833  -3.4333  -4.3606  -1.6167   0.5833 

````

**Comment by yiwenw3** [comment] 2022-02-28 04:46
Thanks for your quick reponse@rafapereirabr! Now I understand the differences between these two models! I also tried to write a "for" loop to extract the IDs I want in `travel_time_matrix()` function. I can receive the travel times, but they are different from the results from the above code, can you please check the issue for me? 

```
ListOfTravelTimes = (matrix(ncol = 3,nrow = 0))
start = 1
end = 25
for (i in start:end) {
  
  OriginPoint = poi[i,2:4]
  DestinationPoint = poi[i,5:7]
  Time_of_Trip = poi[i,9]
  departure_datetime = as.POSIXct(Time_of_Trip[[1]], format = "%m/%d/%Y %H:%M")
  
  ttm <- travel_time_matrix(r5r_core = r5r_core,
                            origins = OriginPoint,
                            destinations = DestinationPoint,
                            mode = mode,
                            departure_datetime = departure_datetime,
                            max_walk_dist = max_walk_dist,
                            max_trip_duration = max_trip_duration,
                            breakdown = FALSE,
                            verbose = FALSE)
  ListOfTravelTimes = rbind(ListOfTravelTimes, as.matrix(ttm))
}
ttm1 = as.data.frame(ListOfTravelTimes)

```

Another question is when I analyze the trip times, which output is better, the ones I received from `travel_time_matrix()` or from `detailed_itineraries()`?

**Comment by rafapereirabr** [comment] 2022-03-01 13:40
Hi @yiwenw3 . Regarding your first question, this latest code you pasted above uses different departure times for each origin-destination pair, while I was using a single departur time for all queries. This is pobably the cause of the difference between our results.

Regarding your second question, if you are only interested in travel time estimates, then I'd recommend using the `travel_time_matrix()` function.

It looks that we can close this issue now, correct?

**Comment by yiwenw3** [comment] 2022-03-01 20:05
Yes! Thank you for the clarification!

**Closed** 2022-03-01 22:43 UTC
