### ISSUE TITLE
Same travel time output for two different modes 

### ISSUE THREAD

**Issue by Onnene** [ipeaGIT/r5r#200] opened 2021-09-12 17:25 UTC
Hi, using the code snippet below I have a situation where I get the same travel time result for TRANSIT and WALK are the same. Are you able to point me in the right direction as to why this occurs? Similar behaviour is experienced when the modes are initially defined as an array then assigned to the mode variable within the travel_time_matrix function. I am happy to provide additional information if you need it. 

```
...

# calculate a travel time matrix

ttmw <- travel_time_matrix(r5r_core = r5r_core,
                          origins = points,
                          destinations = points,
                          mode = "WALK",
                          departure_datetime = departure_datetime,
                          max_walk_dist = md,
                          max_trip_duration = mtd,
                          verbose = FALSE)


ttmt <- travel_time_matrix(r5r_core = r5r_core,
                          origins = points,
                          destinations = points,
                          mode = "TRANSIT",
                          departure_datetime = departure_datetime,
                          max_walk_dist = md,
                          max_trip_duration = mtd,
                          verbose = FALSE)

...

```

**Comment by mvpsaraiva** [comment] 2021-09-12 19:01
Hi @Onnene. When you input `mode = "TRANSIT"`, `r5r` actually considers `mode = c("WALK", "TRANSIT")` because walking between origin/destination points and transit stops needs to be accounted for. Because of that, it's possible that a query of travel times by transit includes some direct walking trips if that's faster than waiting for a transit service. 

Having said that, what I think is going on is that you're getting walking only trips from both `travel_time_matrix()` calls, which can happen if the value passed to `departure_datetime` is outside the date range of the input `GTFS` data. So, just check if your `GTFS` covers the period you're querying for and let us know if that's the problem. I hope this helps.

**Comment by Onnene** [comment] 2021-09-12 20:51
Hello, @mvpsaraiva, thanks for your very quick response. Indeed my `departure_datetime` was outside the date range of the GTFS file. However, the results are still the same after I correct the date.

**Comment by mvpsaraiva** [comment] 2021-09-12 21:31
That was my best guess, but I can't think of anything else without a reproducible example. Can you provide one?

**Comment by Onnene** [comment] 2021-10-08 13:03
@mvpsaraiva, sorry for the late reply, I was away. Please see the example below I am also attaching the GTFS data

```
options(java.parameters = "-Xmx2G")

library(r5r)
library(sf)
#above line not required for now

library(data.table)

data_path <- system.file("extdata/Kigali", package = "r5r")

#debugging line to check its running correctly
list.files(data_path)

points <- fread(file.path(data_path, "Zonal_Centroid.csv"))

#debugging line to check its running correctly
head(points)

# Indicate the path where OSM and GTFS data are stored
r5r_core <- setup_r5(data_path = data_path, verbose = FALSE)

# set inputs "23-11-2020 14:00:00"  "15-04-2019 14:00:00"   "Etc/GMT-2"   "Africa/Kigali"   "America/Sao_Paulo"
# departure_datetime <- as.POSIXct("01-01-2014 07:30:00",format = "%d-%m-%Y %H:%M:%S",tz="Africa/Nairobi")
departure_datetime <- as.POSIXct("17-12-2020 09:30:00",format = "%d-%m-%Y %H:%M:%S", tz="Africa/Kigali")

# sets the maximum walking distance in meters (to allow a cap to the walking distance)
md <- 3000

# sets the maximum trip duration in minutes (to allow a cap to the trip duration)
mtd <- 60

# mode <- c("WALK", "TRANSIT", "BICYCLE", "CAR", "MOTORBIKE")

# calculate a travel time matrix
ttmw <- travel_time_matrix(r5r_core = r5r_core,
                          origins = points,
                          destinations = points,
                          mode = "WALK",
                          departure_datetime = departure_datetime,
                          max_walk_dist = md,
                          max_trip_duration = mtd,
                          verbose = FALSE)

#debugging line which show a few lines of the travel time output per mode
head(ttmw)

# calculate a travel time matrix
ttmt <- travel_time_matrix(r5r_core = r5r_core,
                          origins = points,
                          destinations = points,
                          mode = "TRANSIT",
                          departure_datetime = departure_datetime,
                          max_trip_duration = mtd,
                          verbose = FALSE)

head(ttmt)

# calculate a travel time matrix
ttmb <- travel_time_matrix(r5r_core = r5r_core,
                           origins = points,
                           destinations = points,
                           mode = "BICYCLE",
                           departure_datetime = departure_datetime,
                           max_trip_duration = mtd,
                           verbose = FALSE)

head(ttmb)

# calculate a travel time matrix
ttmc <- travel_time_matrix(r5r_core = r5r_core,
                           origins = points,
                           destinations = points,
                           mode = "CAR",
                           departure_datetime = departure_datetime,
                           max_trip_duration = mtd,
                           verbose = FALSE)

head(ttmc)

# calculate a travel time matrix
ttbs <- travel_time_matrix(r5r_core = r5r_core,
                           origins = points,
                           destinations = points,
                           mode = "BUS",
                           departure_datetime = departure_datetime,
                           max_trip_duration = mtd,
                           verbose = FALSE)

head(ttbs)

# setwd("C:/Users/prava/Documents/R/OUTPUT")
setwd("C:/Users/NNNOB/Downloads/R_Data/output")
write.csv(ttmw,'TT_Walk.csv')
write.csv(ttmb,'TT_Bicycle.csv')
write.csv(ttmc,'TT_Car.csv')
write.csv(ttmt,'TT_Transit.csv')
write.csv(ttbs,'TT_Bus.csv')

#closes r5r and stops using memory
stop_r5(r5r_core)

#restore the gb limit to its default
rJava::.jgc(R.gc = TRUE)
```

Happy to attach my GTFS feed if it's needed. Thanks

**Comment by Onnene** [comment] 2021-10-16 01:44
@rafapereirabr thanks for replying. Yes, I am willing to share, however, my attempts to upload the files (or the zipped version of it) here fail with an error "is not included in the list". Do you mind if I sent the files to your email?

**Comment by rafapereirabr** [comment] 2021-10-16 22:10
I'm glat we were able to help. I'm closing this issue for now, but please let us know if you find any other problems.

**Closed by rafapereirabr** 2021-10-16 22:10 UTC

**Comment by mvpsaraiva** [comment] 2022-04-12 13:43
You only need the .pbf file. The .mapdb, .mapdb.p and network.dat are created by R5 the first time you run `setup_r5`. If you delete those, R5 will create them again the next time. 
To account for the topography, you need a .tif raster file with elevation data. But this is optional, you can safely ignore it.

**Comment by franciscopasqual** [comment] 2022-04-13 00:18
Hi @mvpsaraiva 

I managed to download a .pbf that covers the entire city and the full GTFS too, but it still returns the same outputs for walk and transit, even for 60 minutes cutoffs and with the departure_datetime inside the range of the GTFS. 

...

departure_datetime <- as.POSIXct("13-05-2019 14:00:00", format = "%d-%m-%Y %H:%M:%S")
max_walk_dist = 2000
max_trip_duration = 60

access_TP_empregos_60min <- accessibility(r5r_core = r5r_core,
                        origins = hex_todos,
                        destinations = hex_empregos,
                        opportunities_colname = "oport",
                        decay_function = "step",
                        cutoffs = 61,
                        mode =  c("TRANSIT"),
                        verbose = FALSE)

access_walk_empregos_60min <- accessibility(r5r_core = r5r_core,
                                          origins = hex_todos,
                                          destinations = hex_empregos,
                                          opportunities_colname = "oport",
                                          decay_function = "step",
                                          cutoffs = 61,
                                          mode =  c("WALK"),
                                          verbose = FALSE)

The .csvs, GTFS and .pbf can be found in this folder, in case you want to check it out: https://drive.google.com/drive/folders/1fbzvWZIExPGwnf-iNpEAlJmKSDLkDQet?usp=sharing

Now I really have no idea of what can be happening, but thanks a lot again!

**Comment by mvpsaraiva** [comment] 2022-04-13 13:31
You are creating a variable called `departure_datetime`, but you are not passing its value to the accessibility function.

Just change the function call to the code below and it should work:

```R
access_TP_empregos_60min <- accessibility(r5r_core = r5r_core,
                                          origins = hex_todos,
                                          destinations = hex_empregos,
                                          departure_datetime = departure_datetime,
                                          opportunities_colname = "oport",
                                          decay_function = "step",
                                          cutoffs = 61,
                                          mode = c("TRANSIT"),
                                          verbose = FALSE)
```

**Comment by franciscopasqual** [comment] 2022-04-14 18:13
Hi Marcus! Thanks a lot, now it worked :) Since I had used the travel_time_matrix function before I thought that the departure_datetime was already specified for whatever came on after. Thanks!
