### ISSUE TITLE
Error in setup_r5() java.lang.NoClassDefFoundError: com/conveyal/file/FileStorage

### ISSUE THREAD

**Issue by temospena** [ipeaGIT/r5r#356] opened 2023-11-27 18:52 UTC
Hi all!

A was about to revisit an old r5r network for a project, and I faced this error when "loading" the already build network.
```
Error in setup_r5(data_path = data_path) : 
  java.lang.NoClassDefFoundError: com/conveyal/file/FileStorage

```

But soon I realized that the error is coming any time I do the `setup_r5()`.

``` r
r5r::r5r_sitrep()
#> $r5r_package_version
#> [1] '1.1.0'
#> 
#> $r5_jar_version
#> character(0)
#> 
#> $java_version
#> [1] "11.0.20.1"
#> 
#> $set_memory
#> [1] "-Xmx512m"
#> 
#> $session_info
#> R version 4.3.2 (2023-10-31)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 22.04.3 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0
#> 
#> locale:
#>  [1] LC_CTYPE=pt_PT.UTF-8          LC_NUMERIC=C                 
#>  [3] LC_TIME=pt_PT.UTF-8           LC_COLLATE=en_US.UTF-8       
#>  [5] LC_MONETARY=pt_PT.UTF-8       LC_MESSAGES=en_US.UTF-8      
#>  [7] LC_PAPER=pt_PT.UTF-8          LC_NAME=pt_PT.UTF-8          
#>  [9] LC_ADDRESS=pt_PT.UTF-8        LC_TELEPHONE=pt_PT.UTF-8     
#> [11] LC_MEASUREMENT=pt_PT.UTF-8    LC_IDENTIFICATION=pt_PT.UTF-8
#> 
#> time zone: Europe/Lisbon
#> tzcode source: system (glibc)
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] styler_1.10.2     digest_0.6.33     fastmap_1.1.1     xfun_0.41        
#>  [5] magrittr_2.0.3    glue_1.6.2        r5r_1.1.0         R.utils_2.12.2   
#>  [9] knitr_1.45        htmltools_0.5.7   rJava_1.0-6       rmarkdown_2.25   
#> [13] lifecycle_1.0.4   cli_3.6.1         R.methodsS3_1.8.2 vctrs_0.6.4      
#> [17] reprex_2.0.2      data.table_1.14.8 withr_2.5.2       compiler_4.3.2   
#> [21] R.oo_1.25.0       R.cache_0.16.0    purrr_1.0.2       rstudioapi_0.15.0
#> [25] tools_4.3.2       evaluate_0.23     yaml_2.3.7        rlang_1.1.2      
#> [29] fs_1.6.3

options(java.parameters = '-Xmx32G') 
library(r5r)
#> Please make sure you have already allocated some memory to Java by running:
#>   options(java.parameters = '-Xmx2G').
#> You should replace '2G' by the amount of memory you'll require. Currently, Java memory is set to -Xmx32G

data_path <- system.file("extdata/poa", package = "r5r")
r5r_core <- r5r::setup_r5(data_path = data_path)
#> Downloading R5 jar file to /usr/local/lib/R/site-library/r5r/jar/r5-v6.9-all.jar
#> Error in r5r::setup_r5(data_path = data_path) : 
#>   java.lang.NoClassDefFoundError: com/conveyal/file/FileStorage

```
Have you seen this before? Any clues?

Thanks!

**Comment by rafapereirabr** [comment] 2023-11-27 18:59
Hi @temospena . I haven't seen this before. Could please try adding `overwrite = TRUE`? This way, **r5r** will overwrite the graph previously built.

```
options(java.parameters = '-Xmx32G') 
library(r5r)

data_path <- system.file("extdata/poa", package = "r5r")
r5r_core <- r5r::setup_r5(data_path = data_path, overwrite = TRUE)
```

**Comment by temospena** [comment] 2023-11-27 19:03
Sure, that was my first thought, and I was ready to rebuild the network. 
But that doesn't seem to be the problem :/

```r
r5r_core <- r5r::setup_r5(data_path = data_path, overwrite = TRUE)
#> Downloading R5 jar file to /usr/local/lib/R/site-library/r5r/jar/r5-v6.9-all.jar
#> Error in r5r::setup_r5(data_path = data_path, overwrite = TRUE) : 
#>   java.lang.NoClassDefFoundError: com/conveyal/file/FileStorage
```

**Comment by rafapereirabr** [comment] 2023-11-27 19:11
hummm. Ok, I also noticed this result in your `r5r::r5r_sitrep()`:

#> $r5_jar_version
#> character(0)

This suggests that the package is not finding the JAR file of R5. In this case, I'd suggest you try running this `r5r::download_r5(force_update = TRUE)`, and then try to read / build the network again.

**Comment by temospena** [comment] 2023-11-27 19:24
Humm, in fact.
I just did `r5r::download_r5(force_update = TRUE)`, but the `$r5_jar_version` is still `character(0)`.
And the error persists.
Let me reboot and I'll try again.

**Comment by temospena** [comment] 2023-11-27 19:49
So, after reboot it was still showing `character(0)` at `$r5_jar_version`.
did this again
``` r
 r5r::download_r5(force_update = TRUE)
#> Downloading R5 jar file to /usr/local/lib/R/site-library/r5r/jar/r5-v6.9-all.jar
#> [1] "/usr/local/lib/R/site-library/r5r/jar/r5-v6.9-all.jar"
```
and was still `character(0)` at `$r5_jar_version`.

but when running with reprex, just noticed a hidden warning that did not show before:
``` r
r5r::download_r5(force_update = TRUE)
#> Downloading R5 jar file to /usr/local/lib/R/site-library/r5r/jar/r5-v6.9-all.jar
#> Warning in utils::download.file(url = file_url, destfile = destfile, mode =
#> "wb", : URL
#> https://github.com/conveyal/r5/releases/download/v6.9/r5-v6.9-all.jar: cannot
#> open destfile '/usr/local/lib/R/site-library/r5r/jar/r5-v6.9-all.jar', reason
#> 'Permission denied'
#> Warning in utils::download.file(url = file_url, destfile = destfile, mode =
#> "wb", : download had nonzero exit status
#> [1] "/usr/local/lib/R/site-library/r5r/jar/r5-v6.9-all.jar"
``` 

So just used sudo in the terminal with `sudo Rscript -e "r5r::download_r5(force_update = TRUE)"` and it finally shows
$r5_jar_version
[1] "6.9"

Now I am having other error, which seems to be related with **folder permissions** (and prob the error from the beginning).
```r 
 r5r_core <- r5r::setup_r5(data_path = data_path)
#> Using cached R5 version from /usr/local/lib/R/site-library/r5r/jar/r5-v6.9-all.jar
#> Error in r5r::setup_r5(data_path = data_path) : 
#>  java.io.IOError: java.io.IOException: Parent folder is not writable: /usr/local/lib/R/site-library/r5r/extdata/poa/poa_osm.pbf.mapdb
```

**Comment by dhersz** [comment] 2023-11-27 20:16
The issue is that r5r tries to download the R5 .jar to the package directory, but this directory is located inside /usr/..., which requires sudo to have any content written to.

We should probably use `tools::R_user_dir()` to cache the jar.

@temospena can you please run `tools::R_user_dir("r5r", which = "cache")` and return back the output? I suppose it's probably  something like `"/home/<your_user>/.cache/R/r5r"`.

**Comment by temospena** [comment] 2023-11-30 10:42
Sure,
it returs:
```r
> tools::R_user_dir("r5r", which = "cache")
[1] "/home/<my_user>/.cache/R/r5r"
```

**Comment by rafapereirabr** [comment] 2023-12-04 19:27
Hi Rosa @temospena. Currently, `r5r` stores the R5 Jar file in a folder inside where the `r5r` packages is installed. You can inspect whether the R5 Jar file file is located in this folder.

Here: `system.file("jar", package = "r5r")` 

Whenever we run `setup_r5()`, the package will either read the Jad file located in this folder, or it will donwload the Jar file and save in this location if if has not been downloaded before. So it is a puzzle to me why `r5r` is not detecting the Jar file. This is why I suggest you to run `download_r5(force_update = TRUE)`, and then check the filder again.

For a shor-term solution, I would suggest to uninstall r5r with `utils::remove.packages('r5r')` and install it again from CRAN.

As a permanent solution, we will making a change to the location where `r5r` caches the Jar file using `tools::R_user_dir()`, as @dhersz suggested. This should fix this issue and make `r5r` in line with more recent good practices from CRAN.

**Comment by temospena** [comment] 2023-12-05 10:19
```r
> utils::remove.packages('r5r')
Removing package from ‘/home/<my_user>/R/x86_64-pc-linux-gnu-library/4.3’
(as ‘lib’ is unspecified)
Error in find.package(pkgs, lib) : there is no package called ‘r5r’
```

I installed `r5r` as a system library (in terminal), not as a user library.
Does this issue has something to do with that?

**Comment by rafapereirabr** [comment] 2023-12-05 11:18
I don't know, really. @dhersz , any thoughts?

**Comment by rafapereirabr** [comment] 2023-12-05 12:52
As of my last commit #[861b4b4](https://github.com/ipeaGIT/r5r/commit/861b4b4082d6faa6d0bd5998cb608a12cacd2952), **r5r** now stores R5 Jar file at `tools::R_user_dir("r5r", which = "cache")`.

@temospena , could you please update to the dev version and try running the code below?

***Important:*** Please mind you that the dev version of r5r now uses JDK v1 instead of JDK 11. So you will need install the new JDK 21, which is freely available from the options below:
- [OpenJDK](https://jdk.java.net/java-se-ri/21)
- [Oracle](https://docs.oracle.com/en/java/javase/21/install/index.html)

**Clean install of dev version**
```
utils::remove.packages('r5r')
devtools::install_github("ipeaGIT/r5r", subdir = "r-package")
```

**Test code**
```` 
options(java.parameters = '-Xmx4G')

library(r5r)

# build transport network
data_path <- system.file("extdata/poa", package = "r5r")
r5r_core <- setup_r5(data_path, overwrite = T)

# load origin/destination points
points <- read.csv(file.path(data_path, "poa_points_of_interest.csv"))

departure_datetime <- as.POSIXct(
  "13-05-2019 14:00:00",
  format = "%d-%m-%Y %H:%M:%S"
)

ttm <- travel_time_matrix(
  r5r_core,
  origins = points,
  destinations = points,
  mode = c("WALK", "TRANSIT"),
  departure_datetime = departure_datetime,
  max_trip_duration = 60, 
  progress = T
)

head(ttm)
````

**Comment by dhersz** [comment] 2023-12-05 15:45
> ```r
> > utils::remove.packages('r5r')
> Removing package from ‘/home/<my_user>/R/x86_64-pc-linux-gnu-library/4.3’
> (as ‘lib’ is unspecified)
> Error in find.package(pkgs, lib) : there is no package called ‘r5r’
> ```
> 
> I installed `r5r` as a system library (in terminal), not as a user library. Does this issue has something to do with that?

Hi @temospena. The issue here is that r5r is saved inside your `/usr/local/` library (the system library saved in `/usr/local/lib/R/site-library/r5r`), but it's trying to remove from the library that first appears in `.libPaths()` (which seems to be use library, saved in `/home/<user>/R/x86_64-pc-linux-gnu-library/4.3`).

In you case, you have two options:

- remove the package from the system library, specifying the system library in the `lib` argument of `remove.packages()`, and then reinstalling the dev version r5r in your system library; or
- install r5r in your user library, in which case both the current CRAN version and the dev version will probably work.

**Comment by temospena** [comment] 2023-12-05 17:08
Hi @rafapereirabr and @dhersz , thank you for your replies!

So, I was able to update java to jdk21 (not easy then to set the profile path but finally figure it out).

If I don't run the  `download_r5(force_update = TRUE)` prior to anything, it doesn't find jar.

But here goes the "reprex" after running that.

```r
> r5r::r5r_sitrep()
$r5r_package_version
[1] ‘1.1.999’

$r5_jar_version
[1] "7.0"

$java_version
[1] "21.0.1"

$set_memory
[1] "-Xmx4G"

$session_info
R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=pt_PT.UTF-8          LC_NUMERIC=C                  LC_TIME=pt_PT.UTF-8           LC_COLLATE=en_US.UTF-8       
 [5] LC_MONETARY=pt_PT.UTF-8       LC_MESSAGES=en_US.UTF-8       LC_PAPER=pt_PT.UTF-8          LC_NAME=pt_PT.UTF-8          
 [9] LC_ADDRESS=pt_PT.UTF-8        LC_TELEPHONE=pt_PT.UTF-8      LC_MEASUREMENT=pt_PT.UTF-8    LC_IDENTIFICATION=pt_PT.UTF-8

time zone: Europe/Lisbon
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.8.0  r5r_1.1.0999

loaded via a namespace (and not attached):
 [1] styler_1.10.2     sass_0.4.7        utf8_1.2.4        digest_0.6.33     magrittr_2.0.3    evaluate_0.23     fastmap_1.1.1    
 [8] R.oo_1.25.0       R.cache_0.16.0    jsonlite_1.8.8    processx_3.8.2    R.utils_2.12.2    backports_1.4.1   ps_1.7.5         
[15] promises_1.2.1    httr_1.4.7        purrr_1.0.2       fansi_1.0.5       jquerylib_0.1.4   cli_3.6.1         rlang_1.1.2      
[22] R.methodsS3_1.8.2 ellipsis_0.3.2    reprex_2.0.2      withr_2.5.2       cachem_1.0.8      yaml_2.3.7        tools_4.3.2      
[29] memoise_2.0.1     checkmate_2.3.1   httpuv_1.6.12     curl_5.1.0        vctrs_0.6.5       R6_2.5.1          mime_0.12        
[36] lifecycle_1.0.4   fs_1.6.3          miniUI_0.1.1.1    pkgconfig_2.0.3   callr_3.7.3       clipr_0.8.0       rJava_1.0-10     
[43] bslib_0.6.0       pillar_1.9.0      later_1.3.1       data.table_1.14.8 glue_1.6.2        Rcpp_1.0.11       xfun_0.41        
[50] tibble_3.2.1      rstudioapi_0.15.0 knitr_1.45        xtable_1.8-4      htmltools_0.5.7   rmarkdown_2.25    compiler_4.3.2 
```

```r
> options(java.parameters = '-Xmx4G')
> library(r5r)
#> Please make sure you have already allocated some memory to Java by running:
#>  options(java.parameters = '-Xmx2G').
#> You should replace '2G' by the amount of memory you'll require. Currently, Java memory is set to -Xmx4G
> # build transport network
> data_path <- system.file("extdata/poa", package = "r5r")
> r5r_core <- setup_r5(data_path, overwrite = T)
#> Using cached R5 version from /home/rosa/.cache/R/r5r/r5-v7.0-all.jar

#> Finished building network.dat at /usr/local/lib/R/site-library/r5r/extdata/poa/network.dat
> # load origin/destination points
> points <- read.csv(file.path(data_path, "poa_points_of_interest.csv"))
> departure_datetime <- as.POSIXct(
+   "13-05-2019 14:00:00",
+   format = "%d-%m-%Y %H:%M:%S"
+ )
> ttm <- travel_time_matrix(
+   r5r_core,
+   origins = points,
+   destinations = points,
+   mode = c("WALK", "TRANSIT"),
+   departure_datetime = departure_datetime,
+   max_trip_duration = 60, 
+   progress = T
+ )
#> Error in .jcall("RJavaTools", "Z", "hasField", .jcast(x, "java/lang/Object"),  : 
  java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "<parameter1>" is null
> head(ttm)
#> Error: object 'ttm' not found

```

It loaded the network! But a different error now .

**Comment by temospena** [comment] 2023-12-05 19:25
> A was about to revisit an old r5r network for a project, and I faced this error when "loading" the already build network.

Nevertheless... the first error no longer shows up, and I am able to re-build the old network and make some detailed itineraries.
Apparently not with the demo poa network.

**Comment by rafapereirabr** [comment] 2023-12-22 19:37
Hi @temospena . You said "If I don't run the download_r5(force_update = TRUE) prior to anything, it doesn't find jar."

I've changed the code to address this, so I believe (hope) this should be fixed now. Could you please try it again?

thanks for your patience, Rosa!

**Comment by temospena** [comment] 2024-01-08 13:57
Hi @rafapereirabr !
Thank you for your patience.

In fact that is fixed, I don't need to run download_r5 anymore.
But I still can't run the demo example without the error:
```r

> ttm <- travel_time_matrix(
+   r5r_core,
+   origins = points,
+   destinations = points,
+   mode = c("WALK", "TRANSIT"),
+   departure_datetime = departure_datetime,
+   max_trip_duration = 60, 
+   progress = T
+ )
Error in .jcall("RJavaTools", "Z", "hasField", .jcast(x, "java/lang/Object"),  : 
  java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "<parameter1>" is null
```

Good news is that I can run other examples (my own).

**Comment by claireboyd** [comment] 2024-01-12 20:04
Hi all! I am hoping to use r5r for a research project and am getting the same error code when I try to run the travel_time_matrix function:
```r
Error in .jcall("RJavaTools", "Z", "hasField", .jcast(x, "java/lang/Object"),  : 
  java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "<parameter1>" is null
```

Weirdly enough, I believe it was working before with the [test code](https://github.com/ipeaGIT/r5r/issues/356#issuecomment-1840736135) that @rafapereirabr posted above, but now it isn't working for either the test code or my own data.

I tried clearing my cache as well as removing and re-installing the package. Any other suggestions on why I might be getting this error message?

For context, here is the situation report:
```r
> r5r::r5r_sitrep()
$r5r_package_version
[1] ‘1.1.999’

$r5_jar_version
[1] "7.0"

$java_version
[1] "21.0.1"

$set_memory
[1] "-Xmx2G"

$session_info
R version 4.3.2 (2023-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.3.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Chicago
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] sf_1.0-15       tigris_2.0.4    lubridate_1.9.3 forcats_1.0.0   stringr_1.5.0   dplyr_1.1.4     purrr_1.0.2     readr_2.1.4     tidyr_1.3.0     tibble_3.2.1    ggplot2_3.4.4  
[12] tidyverse_2.0.0 r5r_1.1.0999    rJava_1.0-10   

loaded via a namespace (and not attached):
 [1] gtable_0.3.4       remotes_2.4.2.1    htmlwidgets_1.6.4  devtools_2.4.5     processx_3.8.2     callr_3.7.3        tzdb_0.4.0         ps_1.7.5           vctrs_0.6.5        tools_4.3.2       
[11] generics_0.1.3     curl_5.2.0         proxy_0.4-27       fansi_1.0.6        pkgconfig_2.0.3    KernSmooth_2.23-22 data.table_1.14.10 checkmate_2.3.1    desc_1.4.3         uuid_1.1-1        
[21] lifecycle_1.0.4    compiler_4.3.2     munsell_0.5.0      httpuv_1.6.13      usethis_2.2.2      htmltools_0.5.7    class_7.3-22       urlchecker_1.0.1   later_1.3.2        pillar_1.9.0      
[31] crayon_1.5.2       ellipsis_0.3.2     classInt_0.4-10    cachem_1.0.8       sessioninfo_1.2.2  wk_0.9.1           mime_0.12          tidyselect_1.2.0   digest_0.6.33      stringi_1.7.12    
[41] fastmap_1.1.1      grid_4.3.2         colorspace_2.1-0   cli_3.6.2          magrittr_2.0.3     pkgbuild_1.4.3     utf8_1.2.4         e1071_1.7-14       withr_2.5.2        promises_1.2.1    
[51] scales_1.2.1       backports_1.4.1    rappdirs_0.3.3     timechange_0.2.0   httr_1.4.7         hms_1.1.3          memoise_2.0.1      shiny_1.8.0        miniUI_0.1.1.1     s2_1.1.6          
[61] profvis_0.3.8      rlang_1.1.3        Rcpp_1.0.12        xtable_1.8-4       glue_1.7.0         DBI_1.2.0          pkgload_1.3.3      rstudioapi_0.15.0  R6_2.5.1           fs_1.6.3          
[71] units_0.8-5  
```

Thanks!

**Comment by rafapereirabr** [comment] 2024-01-13 12:54
Hi @claireboyd , could you please run this line of code and tell us what files are inside the cache dir?

`tools::R_user_dir("r5r", which = "cache") |> list.files()`

**Comment by claireboyd** [comment] 2024-01-15 20:26
Yes! Here is the output of that line of code:
```
"r5-v7.0-all.jar"
```

We were hoping to use a cached version of the jar so that we can eventually scale up and get travel time estimates for a larger dataset, using our cluster for more compute power. Let me know if you need any other context!

**Comment by rafapereirabr** [comment] 2024-01-15 21:15
I've now changed how `r5r` caches the R5 Jar file to make it more consistent / robust across eventual r5r updates. Could you please try it again with the code below?

### Clean install of dev version
```
utils::remove.packages('r5r')
devtools::install_github("ipeaGIT/r5r", subdir = "r-package")
```

### Test code
```
options(java.parameters = '-Xmx4G')

library(r5r)

# build transport network
data_path <- system.file("extdata/poa", package = "r5r")
r5r_core <- setup_r5(data_path, overwrite = T)

# load origin/destination points
points <- read.csv(file.path(data_path, "poa_points_of_interest.csv"))

departure_datetime <- as.POSIXct(
  "13-05-2019 14:00:00",
  format = "%d-%m-%Y %H:%M:%S"
)

ttm <- travel_time_matrix(
  r5r_core,
  origins = points,
  destinations = points,
  mode = c("WALK", "TRANSIT"),
  departure_datetime = departure_datetime,
  max_trip_duration = 60, 
  progress = T
)

head(ttm)
```

**Comment by claireboyd** [comment] 2024-01-15 23:08
Hi @rafapereirabr - thanks for the update! After starting a new R session, I can successfully get to a ttm matrix with the above code as well as for my own data (using a cached r5r jar in my project folder). Thanks again!

**Comment by rafapereirabr** [comment] 2024-01-15 23:24
neat! Glad to hear it worked for you, @claireboyd . Now we just need to know if this new solution works for @temospena . Rosa, would you mind tying this again with the latest version (example code above)?

**Comment by temospena** [comment] 2024-01-18 15:38
Hi Rafael,
It didn't work for me :cry: 
I removed the previous version, updated to newest dev one, and the same error still persists.

```r
tools::R_user_dir("r5r", which = "cache") |> list.files()
[1] "r5_jar_v7.0.0"
options(java.parameters = '-Xmx4G')
library(r5r)
#> Please make sure you have already allocated some memory to Java by running:
#>   options(java.parameters = '-Xmx2G').
#> You should replace '2G' by the amount of memory you'll require. Currently, Java memory is set to -Xmx4G
```
``` r
# build transport network
data_path <- system.file("extdata/poa", package = "r5r")
r5r_core <- setup_r5(data_path, overwrite = T)
#> Downloading R5 jar file to /home/rosa/.cache/R/r5r/r5_jar_v7.0.0/r5-v7.0-all.jar

#> Finished building network.dat at /usr/local/lib/R/site-library/r5r/extdata/poa/network.dat

# load origin/destination points
points <- read.csv(file.path(data_path, "poa_points_of_interest.csv"))

departure_datetime <- as.POSIXct(
  "13-05-2019 14:00:00",
  format = "%d-%m-%Y %H:%M:%S"
)

ttm <- travel_time_matrix(
  r5r_core,
  origins = points,
  destinations = points,
  mode = c("WALK", "TRANSIT"),
  departure_datetime = departure_datetime,
  max_trip_duration = 60, 
  progress = T
)
#> Error in .jcall("RJavaTools", "Z", "hasField", .jcast(x, "java/lang/Object"),  : 
  java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "<parameter1>" is null

head(ttm)
#> Error in eval(expr, envir, enclos): object 'ttm' not found
```

```r
> r5r::r5r_sitrep()
$r5r_package_version
[1] ‘1.1.0.9000’

$r5_jar_version
[1] "7.0"

$java_version
[1] "21.0.1"

$set_memory
[1] "-Xmx4G"

$session_info
R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=pt_PT.UTF-8          LC_NUMERIC=C                  LC_TIME=pt_PT.UTF-8          
 [4] LC_COLLATE=en_US.UTF-8        LC_MONETARY=pt_PT.UTF-8       LC_MESSAGES=en_US.UTF-8      
 [7] LC_PAPER=pt_PT.UTF-8          LC_NAME=pt_PT.UTF-8           LC_ADDRESS=pt_PT.UTF-8       
[10] LC_TELEPHONE=pt_PT.UTF-8      LC_MEASUREMENT=pt_PT.UTF-8    LC_IDENTIFICATION=pt_PT.UTF-8

time zone: Europe/Lisbon
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] r5r_1.1.0.9000 rJava_1.0-10  

loaded via a namespace (and not attached):
 [1] utf8_1.2.4         generics_0.1.3     tidyr_1.3.0        class_7.3-22       KernSmooth_2.23-22
 [6] lattice_0.22-5     digest_0.6.33      magrittr_2.0.3     grid_4.3.2         fastmap_1.1.1     
[11] backports_1.4.1    e1071_1.7-14       DBI_1.2.0          httr_1.4.7         purrr_1.0.2       
[16] fansi_1.0.6        crosstalk_1.2.1    scales_1.3.0       codetools_0.2-19   cli_3.6.2         
[21] mapview_2.11.2     rlang_1.1.3        units_0.8-5        munsell_0.5.0      base64enc_0.1-3   
[26] tools_4.3.2        raster_3.6-26      checkmate_2.3.1    dplyr_1.1.4        colorspace_2.1-0  
[31] curl_5.2.0         vctrs_0.6.5        R6_2.5.1           png_0.1-8          stats4_4.3.2      
[36] proxy_0.4-27       lifecycle_1.0.4    classInt_0.4-10    leaflet_2.2.1      htmlwidgets_1.6.4 
[41] pkgconfig_2.0.3    terra_1.7-65       pillar_1.9.0       glue_1.7.0         data.table_1.14.10
[46] Rcpp_1.0.12        sf_1.0-15          tibble_3.2.1       tidyselect_1.2.0   rstudioapi_0.15.0 
[51] htmltools_0.5.7    leafem_0.2.3       satellite_1.0.4    compiler_4.3.2     sp_2.1-2          

```

**Comment by rafapereirabr** [comment] 2024-01-27 23:29
I assume the error occurs for any transport mode, correct? Does the error persist if you do specify `r5r_core = r5r_core`, like this?

```
ttm <- travel_time_matrix(
  r5r_core = r5r_core,
  origins = points,
  destinations = points,
  mode = c("WALK", "TRANSIT"),
  departure_datetime = departure_datetime,
  max_trip_duration = 60, 
  progress = T
)
```

**Comment by temospena** [comment] 2024-02-06 18:44
Hi, 
I tested with other transport modes, with a single and more than one, and the error was the same.
I added `r5_core = ` and the error was the same again.
:/

**Comment by dhersz** [comment] 2024-04-04 21:01
We were finally able to trace down this issue today.

The error when specifically trying to run the example was the result of `setup_r5()` trying to create the network files inside the package directory, which was installed in a location where @temospena didn't have write permissions. The function would silently fail to build the network and would eventually fail like seen above.

https://github.com/ipeaGIT/r5r/commit/a550daf431e004c08b6ac57b55812f1903a719a5 adds a much more meaningful error messages for situations like that.

We agreed to not change the tests/examples and to keep building the example network inside the package directory, as it makes the examples more user-friendly.

**Closed by dhersz** 2024-04-04 21:01 UTC
Labels: v2.0.0
