### ISSUE TITLE
Calculations not working

### ISSUE THREAD

**Issue by mortewle** [ipeaGIT/r5r#109] opened 2020-09-07 09:37 UTC
Hi,

My travel_time_matrix calculations for public transport do not work properly. The calculations are mostly walking trips, plus a small amount of bus trips. But no subway, tram or ferry trips, even though the study area is Oslo, Norway and c(WALK, "TRANSIT") is specified as mode. My colleague has the same issue. The calculations work with OpenTripPlanner.

I use norway-latest.osm.pbf from geofabrik.de and GTFS (in .zip) from Entur. Here is the script: 

#devtools::install_github("ipeaGIT/r5r", subdir = "r-package")
options(java.parameters = "-Xmx5G")
library(r5r)

# 1) build transport network, pointing to the path where OSM and GTFS data are stored
r5r_core <- setup_r5(data_path = "otp/graphs/default/r5r/")

# 2) load origin/destination points
origins_punkter <- st_read("od/origins_punkter_oslo.gpkg") %>% st_transform(crs = 4326)
destinations_punkter <- st_read("od/destinations_punkter_oslo.gpkg") %>% st_transform(crs = 4326)

#make it r5r-compatible
origins_punkter <- as.data.frame(origins_punkter) %>% separate(geom, c("lon", "lat"), sep = ", ")
origins_punkter$lon <- gsub("[c(]", "" , origins_punkter$lon, perl=TRUE)
origins_punkter$lat <- gsub("[)]", "" , origins_punkter$lat, perl=TRUE)
origins_punkter$id <- as.character(origins_punkter$ori_id)
origins_punkter$lon <- as.numeric(origins_punkter$lon)
origins_punkter$lat <- as.numeric(origins_punkter$lat)
origins_punkter <- dplyr::select(origins_punkter, id, lon, lat)

destinations_punkter <- as.data.frame(destinations_punkter) %>% separate(geom, c("lon", "lat"), sep = ", ")
destinations_punkter$lon <- gsub("[c(]", "" , destinations_punkter$lon, perl=TRUE)
destinations_punkter$lat <- gsub("[)]", "" , destinations_punkter$lat, perl=TRUE)
destinations_punkter$id <- as.character(destinations_punkter$ZONE_ID)
destinations_punkter$lon <- as.numeric(destinations_punkter$lon)
destinations_punkter$lat <- as.numeric(destinations_punkter$lat)
destinations_punkter <- dplyr::select(destinations_punkter, id, lon, lat)

# calculate a travel time matrix
odcostmatrix_offtrans_0800 <- travel_time_matrix(r5r_core,
                          origins = origins_punkter,
                          destinations = destinations_punkter,
                          mode = c("WALK", "TRANSIT"),
                          departure_datetime = lubridate::as_datetime("2020-08-13 08:00:00"),
                          max_walk_dist = 3000,  # meters
                          max_trip_duration = 120, # minutes
                          verbose = FALSE
)

**Comment by rafapereirabr** [comment] 2020-09-08 13:23
Hi @mortewle . Thank you for opening this issue. Would it be possible for you to share with us a link from where we can download the `osm.pbf` and `gtfs.zip` data sets? This is necessary for us to be able to to reproduce these results and investigate the issue.

**Comment by mortewle** [comment] 2020-09-08 13:36
Yes, GTFS for "Entire Norway" from https://developer.entur.org/stops-and-timetable-data.

norway-latest.osm.pbf from https://download.geofabrik.de/europe/norway.html.

Do you need origins and destination points too?

**Comment by rafapereirabr** [comment] 2020-09-08 13:49
We don't need all origins and destination points, but a sample of a few points for which you `r5r`outputs an unxpected routing result would be good.

**Comment by mortewle** [comment] 2020-09-08 13:59
Okay, here are ODs for a 200x400 cost matrix. 

[od.zip](https://github.com/ipeaGIT/r5r/files/5188753/od.zip)

**Comment by mortewle** [comment] 2020-09-08 14:03
Ran the analysis with this sample now, it returned only 267 lines.

**Comment by mvpsaraiva** [comment] 2020-09-08 17:36
Thanks for providing all the data, @mortewle. We are looking into it, but still didn't figure out exactly what's causing the problem. We'll continue testing and will let you know as soon as we find anything.

**Comment by Torskelgen** [comment] 2020-09-09 07:30
Could it be that r5 is more picky than OTP on the gtfs formatting?

**Comment by rafapereirabr** [comment] 2020-09-09 11:22
Hi @Torskelgen ,  yes it seems r5 is picky with GTFS quality, though we're not sure this is the issue here. I know @mvpsaraiva is looking further into this. Meanwhile, I just wanted to flag that 3 issues that might be causing this:

1. `departure_datetime` input could be outside the period of reference in the GTFS `calendar.txt`. This would lead both OTP and R5 to ignore public transport trips.
2. `max_walk_dist` input could possibily be too short given the distances between origins/destinations and public transport entrance/exit points. 
3. `max_trip_duration` could possibily be too short given the distances between origins and destinations

Items 2 and 3 depend on each context of analysis.

**Comment by mortewle** [comment] 2020-09-09 13:11
1. This shouldn't be the case, since OTP managed to find public transport trips, r5r also found some (few) PT trips. 

2. & 3. The max_walk_dist and max_trip_duration selected should be more than enough, I also tried with higher values.

**Comment by mvpsaraiva** [comment] 2020-09-14 14:53
Hi @mortewle. I've finally managed to find the problem.

Basically, your study area is really big, so 120 minutes is not enough time to travel between many of your OD points. The main problem is that there was a hardcoded 120 minutes limit in R5's travel time computations that trumped our own `max_trip_duration` parameter, turning it ineffective for values higher than 120. I've removed that hard limit, and now if you set values higher than that, you'll se r5r returns travel times between a larger set of your OD points. You may want to increase the `max_rides` parameter as well from its default of 3, allowing more transit interchanges and possibly making destinations farther away reachable.

The next time you run `setup_r5()`, the package should download the updated version of r5r's java backend with those changes. You can also run `download_r5()` to do that. 

Please, let us know if this solves your problem.

**Comment by mortewle** [comment] 2020-09-14 22:07
Hi, 

Thank you for investigating my issue. Unfortunately, it still doesn't work. The problem isn't that the cutoff is too low, but that very few transit trips are calculated. When testing with different transport modes, I actually get fewer OD lines with mode=c("WALK", "TRANSIT") than mode="WALK" when using max_walk_dist=6000, max_trip_duration=180 and max_rides=10. Also, I get the same results with mode=c("WALK", "TRANSIT") and mode=c("WALK", "BUS").

**Comment by mvpsaraiva** [comment] 2020-09-16 23:07
Hi @mortewle. I did some more tests with different transport modes, using mode=c("WALK", **mode below**), `max_walk_dist=3000`, `max_trip_duration=240`, and `max_rides=3`. For each mode, I got the following number of OD pairs:

| Mode    | OD results |
|---------|-----------:|
| Transit |     13,229 |
| Bus     |      8,450 |
| Rail    |       3959 |
| Subway  |        183 |
| Ferry   |        194 |

Those values seem quite low, but the number of trips found follow the expected distribution. I also cranked up `max_trip_duration` to 720 minutes, and set `max_rides=10`, to get a matrix with 72,622 lines. I didn't manage to get the complete 80,000 trips from the input dataset, though, even with settings higher than those. 

I've investigated further, as those travel times seemed quite overestimated. The longest trip I got was between points 4385 to 989, with a travel time of 774 minutes. A `detailed_itineraries()` query between those points produce a trip with similar duration, containing one rail segment and 3 bus segments, plus the walking transfers between stops and stations. The segment themselves seem to have accurate durations, but there is a crazy 477 minutes wait for the first bus, that you can see in the image below. For now, I have no idea what's causing that long wait, but I guess this problem is happening between many of the OD points.
 
<img width="660" alt="Screenshot 2020-09-16 at 19 55 05" src="https://user-images.githubusercontent.com/7387691/93400605-8a562a00-f856-11ea-8322-d94abd92a8be.png">

I'll keep investigating, but please let us know if you have any clue on what's going on. I suspect it has something to do with the GTFS, and the fact that R5 is more picky than OTP regarding the GTFS. One thing I noticed is that the ENTUR GTFS files are updated quite frequently. So, with the file I downloaded, the date you provided (2020-08-13) didn't return any results. I had to do the queries for 2020-09-08. That's probably something else that needs to be checked.

**Comment by mvpsaraiva** [comment] 2020-09-17 17:29
I believe we found the final bug in this issue. Due to the timezone differences between Brazil and Norway, my queries were being carried out in the middle of the night (3am), hence the long waiting times for the first transit services in the morning. After the last package update, I've got the following results for a query at 8am:

| Mode    | OD results |
|---------|-----------:|
| Transit |     29,436 |
| Bus     |      19,420 |
| Rail    |       5,833 |
| Subway  |        183 |
| Ferry   |        193 |

The query from point 4385 to 989, departing at noon, now produced reasonable trip duration and waiting times:

<img width="727" alt="Screenshot 2020-09-17 at 14 25 40" src="https://user-images.githubusercontent.com/7387691/93505870-d2765a80-f8f1-11ea-8e94-29f3ff0b4907.png">

**Comment by mortewle** [comment] 2020-09-19 07:56
Yes, now it works, thank you! 

A travel_time_matrix for a smaller area (Oslo) returned 100% of the maximum amount of OD lines with 180 minutes cutoff and 90% with 60 minutes cutoff. For mode="WALK", it returned 94 and 24 percent. The travel times from the detailed_itineraries also make sense.

**Comment by rafapereirabr** [comment] 2020-09-19 18:30
Thank you @mortewle. Thanks to your question we are improving this time zone issue in the next version of `r5r`. Special thanks to @mvpsaraiva and @dhersz for solving this! Closing this issue now.

**Closed by rafapereirabr** 2020-09-19 18:30 UTC
